    #cloud-config
    #separated out for linting
    bootcmd:
      - ln -s /dev/null /etc/systemd/system/avahi-daemon.service
    apt:
      sources:
        maasnext:
          source: "ppa:maas/next"
    package_upgrade: true
    packages:
      - bridge-utils
      - maas
      - qemu-kvm
      - libvirt-bin
      - virtinst
    write_files:
      - content: |
          <network>
          <name>maas</name>
          <forward mode="bridge"/>
          <bridge name="br0"/>
          </network>
        path: /var/lib/libvirt/qemu/network.xml
    runcmd:
      - [systemctl, restart, networking.service]
      - [maas, createadmin, --username=admin, --password=admin, --email=admin]
      - [adduser, maas, libvirtd]
      - [skill, -KILL, -u, maas]
      - [virsh, net-define, /var/lib/libvirt/qemu/network.xml]
      - [virsh, net-autostart, maas]
      - [virsh, net-start, maas]
      - [virsh, net-destroy, default]
      - [virsh, net-undefine, default]
      - [virsh, pool-define-as, default, dir, --target, /var/lib/libvirt/images/]
      - [virsh, pool-autostart, default]
      - [virsh, pool-start, default]